version: 2

project_name: dockmate

before:
  hooks:
    - go mod tidy

builds:
  - binary: dockmate
    main: .
    goos:
      - linux
      - darwin  # ADD THIS (for macOS)
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: binary
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

# ADD THIS ENTIRE SECTION
brews:
  - repository:
      owner: shubh-io
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/shubh-io/DockMate"
    description: "Docker container monitoring TUI"
    license: "MIT"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    test: |
      system "#{bin}/dockmate --version"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  github:
    owner: shubh-io
    name: dockmate
